### ISSUE TITLE
Difference between Kotlin Value Classes and Value4k

### ISSUE THREAD

**Issue by qoomon** [fork-handles/forkhandles#33]
What is the difference between [Kotlin Value Classes](https://kotlinlang.org/docs/inline-classes.html) and the [Values4k](https://github.com/fork-handles/forkhandles/tree/trunk/values4k) approach?

**Comment by daviddenton** [comment]
you can use values4k with or without Kotlin value classes. You basically have 2 options, both of which will work with the ValueFactory machinery that values4k provides:

1. Value classes implementing the `Value` interface
2. Non-value classes extending the `AbstractValue` superclass

You are free to choose either. However - in the event that you are using any type of auto-marshalling technology (such as Jackson or anything else which reflectively constructs class instances from JSON or other ) you will have issues because the validation and other facilities which are provided by the library will be ignored (as the Kotlin complier will throw away the controlled instantiation at compile time and the type replaced with the underlying raw type instead).

Value classes are very useful, but also the JVM is incredibly good at optimising code so most applications will only benefit negligibly from their use and this may be outweighed by the losses detailed above.

Closing this off, but feel free to continue the discussion! 😄

**Comment by qoomon** [comment]
Thanks for clarifying.
